name: 17 - custom Actons - composite

on: 
    workflow_dispatch:

env:
    working-directory: 17-custom-actions/react-app 

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{env.working-directory}}
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-dependencies
              with: 
                node-version: 20.x
                working-dir: ${{env.working-directory}}
            - name: test
              run: npm run build
            - name: Build
              run: npm run build