name: Build, Push and deploy to ECS
on:
  push:
    branches:
      - deployment-automation
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - bvv
          - will_be_in_future
      release_tag:
        description: 'Git release tag (leave empty to fetch all tags)'
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Fetch all tags
        run: |
          git fetch --tags
          echo "Available tags:"
          git tag
